### ISSUE TITLE
xls file throws no error, but no cell data retrieved ("Los Alamos sheet")

### ISSUE THREAD

**Issue by jennybc** [evanmiller/libxls#28] opened 2018-12-14 01:25 UTC
Original readxl issue: https://github.com/tidyverse/readxl/issues/483

File is "ctl_summary.xls" available from the top xls link here:
https://www.hiv.lanl.gov/content/immunology/tables/ctl_summary.html

With xls2csv built from https://github.com/evanmiller/libxls/commit/b20521f964d0c22b45db0b8c97a9d777bccd0f7f, I see this:

```
jenny@2015-mbp libxls-evanmiller-github $ ./xls2csv ~/rrr/readxl/investigations/ctl_summary.xls
FILE: /Users/jenny/rrr/readxl/investigations/ctl_summary.xls
```

No error, but also no data. 

Using `xls2csv` with the `-v` verbose flag reveals the file is being parsed but somehow no data comes out.

**Comment by evanmiller** [comment] 2018-12-14 01:36
Duplicate of #27. Should be fixed now. Please test & confirm.

**Closed by evanmiller** 2018-12-14 01:36 UTC

**Comment by jennybc** [comment] 2018-12-14 02:15
Yep, fixed. Thanks!
